# golangci-lint configuration for v2.x
# https://golangci-lint.run/usage/configuration/

version: 2

run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    # Default linters (already enabled)
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused

    # Additional linters
    - bodyclose
    - gosec
    - goconst
    - misspell
    - revive
    - unconvert
    - predeclared
    - nilerr

  disable:
    - exhaustive
    - funlen
    - gocyclo
    - lll

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

  govet:
    enable:
      - shadow

  gosec:
    excludes:
      - G404 # Weak random OK for non-crypto use

  revive:
    confidence: 0.8

  misspell:
    locale: US

  goconst:
    min-len: 3
    min-occurrences: 3

issues:
  exclude-use-default: false
  exclude-rules:
    # Exclude linters from test files
    - path: _test\.go
      linters:
        - gosec
        - errcheck
        - goconst
        - unused

    # Exclude from test directory
    - path: test/
      linters:
        - errcheck
        - gosec
        - unused

    # Exclude from examples
    - path: cmd/examples/
      linters:
        - errcheck
        - gosec
        - goconst
        - unused
        - staticcheck

  max-issues-per-linter: 0
  max-same-issues: 0

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true
